name: lightning_db
description: High-performance embedded database for Dart and Flutter applications
version: 0.1.0
homepage: https://github.com/your-org/lightning_db

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  ffi: ^2.1.0
  meta: ^1.11.0

dev_dependencies:
  ffigen: ^11.0.0
  lints: ^3.0.0
  test: ^1.24.0