name: lightning_db_workspace
repository: https://github.com/santoshakil/lightning_db

packages:
  - packages/*
  - packages/*/example

scripts:
  analyze:
    exec: dart analyze
    description: Analyze all packages
  
  test:
    exec: dart test
    description: Run tests for all packages
  
  format:
    exec: dart format .
    description: Format all Dart code
  
  build:
    exec: dart run build_runner build --delete-conflicting-outputs
    description: Run code generation
    packageFilters:
      dependsOn: build_runner
  
  clean:
    run: melos exec -c 1 -- "flutter clean"
    description: Clean all packages
  
  pub:
    run: melos exec -c 1 -- "flutter pub get"
    description: Get dependencies for all packages

command:
  bootstrap:
    usePubspecOverrides: true
  
  version:
    message: |
      chore: release version
      
      All packages have been versioned