name: lightning_db_dart
description: "Dart FFI bindings for Lightning DB - a high-performance embedded database"
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.8.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  ffi: ^2.1.3
  meta: ^1.9.0

dev_dependencies:
  ffigen: 19.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0
  test: ^1.25.15

ffigen:
  name: LightningDbBindings
  description: Bindings for `src/lightning_db_ffi.h`.
  output: 'lib/lightning_db_bindings_generated.dart'
  headers:
    entry-points:
      - 'src/lightning_db_ffi.h'
    include-directives:
      - 'src/lightning_db_ffi.h'
  preamble: |
    // ignore_for_file: always_specify_types
    // ignore_for_file: camel_case_types
    // ignore_for_file: non_constant_identifier_names
  comments:
    style: any
    length: full
  silence-enum-warning: true

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true