# Lightning DB Production Configuration

[database]
data_dir = "/app/data"
max_memory = "2GB"
cache_size = "512MB"
page_size = 4096
enable_wal = true
sync_writes = true
checkpoint_interval = 120  # 2 minutes
auto_vacuum = true

[storage]
max_file_size = "1GB"
compaction_threshold = 0.3
enable_compression = true
compression_algorithm = "zstd"
compression_level = 6  # Higher compression for production
encryption_enabled = true

[performance]
read_threads = 8
write_threads = 4
compaction_threads = 4
io_uring_enabled = true
prefetch_enabled = true
cache_warmup_enabled = true
batch_size = 10000
numa_aware = true

[monitoring]
metrics_enabled = true
metrics_port = 9090
health_check_port = 8080
prometheus_endpoint = "/metrics"
detailed_metrics = false  # Reduce overhead in production
tracing_enabled = true
trace_sampling_rate = 0.01  # 1% sampling

[logging]
level = "warn"
format = "json"
output = "file"
log_file = "/app/logs/lightning_db.log"
log_rotation = true
max_log_size = "1GB"
max_log_files = 30
log_queries = false
log_slow_queries = true
slow_query_threshold = 10  # 10ms
structured_logging = true

[security]
enable_tls = true
cert_file = "/app/certs/tls.crt"
key_file = "/app/certs/tls.key"
ca_file = "/app/certs/ca.crt"
enable_auth = true
auth_method = "jwt"
session_timeout = 3600  # 1 hour
audit_logging = true
rate_limiting = true
max_connections = 10000
connection_timeout = 30
idle_timeout = 300

[replication]
enabled = true
replication_factor = 3
consistency_level = "strong"
sync_replication = true

[backup]
enabled = true
backup_interval = 1800  # 30 minutes
backup_retention = 720  # 30 days in hours
backup_compression = true
backup_encryption = true
incremental_backups = true
point_in_time_recovery = true

[features]
experimental_features = false
unsafe_optimizations = false
debug_mode = false
production_mode = true

[resource_limits]
max_memory_usage = "1.8GB"  # 90% of max_memory
max_disk_usage = "80%"
max_cpu_usage = "80%"
connection_pool_size = 100