# Lightning DB Production Configuration

[database]
# Core database settings
cache_size_mb = 512
max_active_transactions = 10000
page_size = 4096

# Performance settings
prefetch_enabled = true
prefetch_distance = 16
prefetch_workers = 4

# Compression
compression_enabled = true
compression_type = "zstd"  # zstd, lz4, or none

[wal]
# Write-ahead log configuration
enabled = true
sync_mode = "async"  # sync, async, or fsync
improved_wal = true
group_commit = true
segment_size_mb = 64

[transaction]
# Transaction management
isolation_level = "snapshot"
conflict_detection = "optimistic"
cleanup_interval_seconds = 30
version_retention_seconds = 300

[cache]
# Cache configuration
algorithm = "arc"  # ARC (Adaptive Replacement Cache)
eviction_policy = "lru"
batch_eviction = true
eviction_batch_size = 100

[monitoring]
# Monitoring and observability
metrics_enabled = true
metrics_port = 9090
health_check_interval_seconds = 30
statistics_collection_interval_seconds = 10

[logging]
# Logging configuration
level = "info"  # trace, debug, info, warn, error
format = "json"
file = "/data/logs/lightning-db.log"
max_file_size_mb = 100
max_files = 10
compress_rotated = true

[backup]
# Backup configuration
enabled = true
directory = "/data/backups"
schedule = "0 2 * * *"  # Daily at 2 AM
retention_days = 30
compress = true
verify = true

[limits]
# Resource limits
max_memory_mb = 2048
max_disk_usage_gb = 100
max_connections = 1000
rate_limit_ops_per_second = 100000

[security]
# Security settings
admin_api_enabled = true
admin_api_port = 8080
health_check_enabled = true
metrics_endpoint_enabled = true
require_auth = false  # Set to true for production with auth

[advanced]
# Advanced settings (use with caution)
use_lock_free_structures = true
enable_simd_optimizations = true
zero_copy_enabled = true
background_compaction = true
parallel_compaction_workers = 2