# Lightning DB Staging Configuration

[database]
data_dir = "/app/data"
max_memory = "1GB"
cache_size = "256MB"
page_size = 4096
enable_wal = true
sync_writes = true
checkpoint_interval = 180  # 3 minutes

[storage]
max_file_size = "500MB"
compaction_threshold = 0.4
enable_compression = true
compression_algorithm = "zstd"
compression_level = 3

[performance]
read_threads = 4
write_threads = 2
compaction_threads = 2
io_uring_enabled = true
prefetch_enabled = true
cache_warmup_enabled = true
batch_size = 1000

[monitoring]
metrics_enabled = true
metrics_port = 9090
health_check_port = 8080
prometheus_endpoint = "/metrics"
detailed_metrics = true
tracing_enabled = true

[logging]
level = "info"
format = "json"
output = "file"
log_file = "/app/logs/lightning_db.log"
log_rotation = true
max_log_size = "100MB"
max_log_files = 10
log_queries = false
log_slow_queries = true
slow_query_threshold = 50  # 50ms

[security]
enable_tls = true
cert_file = "/app/certs/tls.crt"
key_file = "/app/certs/tls.key"
enable_auth = true
audit_logging = true
rate_limiting = true
max_connections = 1000

[replication]
enabled = false

[backup]
enabled = true
backup_interval = 3600  # 1 hour
backup_retention = 168  # 7 days in hours
backup_compression = true
backup_encryption = true

[features]
experimental_features = false
unsafe_optimizations = false
debug_mode = false