# Lightning DB Development Configuration

[database]
data_dir = "/app/data"
max_memory = "512MB"
cache_size = "128MB"
page_size = 4096
enable_wal = true
sync_writes = false  # Faster for development
checkpoint_interval = 300  # 5 minutes

[storage]
max_file_size = "100MB"
compaction_threshold = 0.5
enable_compression = true
compression_algorithm = "lz4"  # Fast compression for dev

[performance]
read_threads = 2
write_threads = 1
compaction_threads = 1
io_uring_enabled = false  # Simpler setup for dev
prefetch_enabled = true
cache_warmup_enabled = false

[monitoring]
metrics_enabled = true
metrics_port = 9090
health_check_port = 8080
prometheus_endpoint = "/metrics"
detailed_metrics = true

[logging]
level = "debug"
format = "pretty"  # Human readable for development
output = "stdout"
log_queries = true
log_slow_queries = true
slow_query_threshold = 100  # 100ms

[security]
enable_tls = false  # Disabled for development
enable_auth = false
audit_logging = false
rate_limiting = false

[replication]
enabled = false

[backup]
enabled = false

[features]
experimental_features = true
unsafe_optimizations = false
debug_mode = true