groups:
  - name: lightning_db_performance
    rules:
      # High-level performance metrics
      - record: lightning_db:read_latency_p99
        expr: histogram_quantile(0.99, rate(lightning_db_read_duration_seconds_bucket[5m]))
      
      - record: lightning_db:write_latency_p99
        expr: histogram_quantile(0.99, rate(lightning_db_write_duration_seconds_bucket[5m]))
      
      - record: lightning_db:read_rate
        expr: rate(lightning_db_reads_total[5m])
      
      - record: lightning_db:write_rate
        expr: rate(lightning_db_writes_total[5m])
      
      - record: lightning_db:error_rate
        expr: rate(lightning_db_errors_total[5m])
      
      # Cache performance
      - record: lightning_db:cache_hit_rate
        expr: rate(lightning_db_cache_hits_total[5m]) / (rate(lightning_db_cache_hits_total[5m]) + rate(lightning_db_cache_misses_total[5m]))
      
      # Memory utilization
      - record: lightning_db:memory_utilization
        expr: lightning_db_memory_used_bytes / lightning_db_memory_total_bytes
      
      # Disk utilization
      - record: lightning_db:disk_utilization
        expr: lightning_db_disk_used_bytes / lightning_db_disk_total_bytes

  - name: lightning_db_alerts
    rules:
      # Critical alerts
      - alert: LightningDBDown
        expr: up{job="lightning-db"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Lightning DB instance is down"
          description: "Lightning DB instance {{ $labels.instance }} has been down for more than 1 minute."
      
      - alert: LightningDBHighErrorRate
        expr: lightning_db:error_rate > 0.1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High error rate in Lightning DB"
          description: "Lightning DB instance {{ $labels.instance }} has error rate of {{ $value }} errors/sec for more than 5 minutes."
      
      - alert: LightningDBHighLatency
        expr: lightning_db:read_latency_p99 > 0.001 or lightning_db:write_latency_p99 > 0.01
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High latency in Lightning DB"
          description: "Lightning DB instance {{ $labels.instance }} has high latency: read p99={{ $labels.read_p99 }}s, write p99={{ $labels.write_p99 }}s"
      
      # Resource alerts
      - alert: LightningDBHighMemoryUsage
        expr: lightning_db:memory_utilization > 0.9
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage in Lightning DB"
          description: "Lightning DB instance {{ $labels.instance }} memory usage is {{ $value | humanizePercentage }} for more than 10 minutes."
      
      - alert: LightningDBHighDiskUsage
        expr: lightning_db:disk_utilization > 0.85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High disk usage in Lightning DB"
          description: "Lightning DB instance {{ $labels.instance }} disk usage is {{ $value | humanizePercentage }} for more than 5 minutes."
      
      - alert: LightningDBLowCacheHitRate
        expr: lightning_db:cache_hit_rate < 0.8
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: "Low cache hit rate in Lightning DB"
          description: "Lightning DB instance {{ $labels.instance }} cache hit rate is {{ $value | humanizePercentage }} for more than 15 minutes."
      
      # Connection alerts
      - alert: LightningDBHighConnectionCount
        expr: lightning_db_active_connections > 8000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High connection count in Lightning DB"
          description: "Lightning DB instance {{ $labels.instance }} has {{ $value }} active connections for more than 5 minutes."
      
      # Backup alerts
      - alert: LightningDBBackupFailed
        expr: increase(lightning_db_backup_failures_total[1h]) > 0
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: "Lightning DB backup failed"
          description: "Lightning DB backup failed on instance {{ $labels.instance }}."
      
      - alert: LightningDBBackupOld
        expr: time() - lightning_db_last_backup_timestamp > 3600 * 6  # 6 hours
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: "Lightning DB backup is old"
          description: "Lightning DB last backup was {{ $value | humanizeDuration }} ago on instance {{ $labels.instance }}."

  - name: kubernetes_resources
    rules:
      # Pod resource usage
      - alert: PodHighCPUUsage
        expr: (rate(container_cpu_usage_seconds_total{pod=~"lightning-db-.*"}[5m]) * 100) > 80
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Pod high CPU usage"
          description: "Pod {{ $labels.pod }} CPU usage is {{ $value }}% for more than 10 minutes."
      
      - alert: PodHighMemoryUsage
        expr: (container_memory_working_set_bytes{pod=~"lightning-db-.*"} / container_spec_memory_limit_bytes{pod=~"lightning-db-.*"}) * 100 > 90
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Pod high memory usage"
          description: "Pod {{ $labels.pod }} memory usage is {{ $value }}% for more than 5 minutes."
      
      - alert: PodRestarting
        expr: increase(kube_pod_container_status_restarts_total{pod=~"lightning-db-.*"}[15m]) > 0
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: "Pod is restarting"
          description: "Pod {{ $labels.pod }} restarted {{ $value }} times in the last 15 minutes."