name: lightning_db_freezed
version: 0.1.0
description: Freezed integration for Lightning DB - Seamless support for immutable data models
homepage: https://github.com/santoshakil/lightning_db
repository: https://github.com/santoshakil/lightning_db

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  freezed_annotation: ^2.4.0
  json_annotation: ^4.8.0
  lightning_db_dart:
    path: ../lightning_db_dart
  meta: ^1.11.0
  rxdart: ^0.27.7

dev_dependencies:
  build_runner: ^2.4.0
  freezed: ^2.4.0
  json_serializable: ^6.7.0
  test: ^1.24.0
  lints: ^3.0.0