apiVersion: v1
kind: Namespace
metadata:
  name: lightning-db
  labels:
    name: lightning-db
    app.kubernetes.io/name: lightning-db
    app.kubernetes.io/component: database
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: lightning-db-quota
  namespace: lightning-db
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    pods: "10"
    services: "5"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: lightning-db-limits
  namespace: lightning-db
spec:
  limits:
  - default:
      cpu: "1"
      memory: 2Gi
    defaultRequest:
      cpu: 500m
      memory: 512Mi
    type: Container