apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lightning-db-data
  namespace: lightning-db
  labels:
    app.kubernetes.io/name: lightning-db
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fast-ssd
  resources:
    requests:
      storage: 100Gi
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast-ssd
  labels:
    app.kubernetes.io/name: lightning-db
    app.kubernetes.io/component: storage-class
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp3
  iops: "3000"
  throughput: "125"
  encrypted: "true"
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lightning-db-backup
  namespace: lightning-db
  labels:
    app.kubernetes.io/name: lightning-db
    app.kubernetes.io/component: backup-storage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 500Gi