apiVersion: v1
kind: ServiceAccount
metadata:
  name: lightning-db
  namespace: lightning-db
  labels:
    app.kubernetes.io/name: lightning-db
    app.kubernetes.io/component: service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: lightning-db
  name: lightning-db-role
  labels:
    app.kubernetes.io/name: lightning-db
    app.kubernetes.io/component: rbac
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lightning-db-rolebinding
  namespace: lightning-db
  labels:
    app.kubernetes.io/name: lightning-db
    app.kubernetes.io/component: rbac
subjects:
- kind: ServiceAccount
  name: lightning-db
  namespace: lightning-db
roleRef:
  kind: Role
  name: lightning-db-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lightning-db-cluster-role
  labels:
    app.kubernetes.io/name: lightning-db
    app.kubernetes.io/component: rbac
rules:
- apiGroups: [""]
  resources: ["nodes", "nodes/metrics"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["nodes", "pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lightning-db-cluster-rolebinding
  labels:
    app.kubernetes.io/name: lightning-db
    app.kubernetes.io/component: rbac
subjects:
- kind: ServiceAccount
  name: lightning-db
  namespace: lightning-db
roleRef:
  kind: ClusterRole
  name: lightning-db-cluster-role
  apiGroup: rbac.authorization.k8s.io