global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "lightning_db_alerts.yml"

scrape_configs:
  # Lightning DB metrics
  - job_name: 'lightning-db'
    static_configs:
      - targets: ['lightning-db:9090']
    scrape_interval: 5s
    metrics_path: /metrics
    
  # System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093