name: lightning_db
version: 0.1.0
description: Lightning DB Flutter plugin - High-performance embedded database for Flutter
homepage: https://github.com/santoshakil/lightning_db
repository: https://github.com/santoshakil/lightning_db

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  lightning_db_dart:
    path: ../lightning_db_dart
  lightning_db_freezed:
    path: ../lightning_db_freezed
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.lightningdb.flutter
        pluginClass: LightningDbPlugin
        ffiPlugin: true
      ios:
        pluginClass: LightningDbPlugin
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        pluginClass: LightningDbPlugin
        ffiPlugin: true
      windows:
        ffiPlugin: true