[target.aarch64-apple-ios]
rustflags = [
    "-C", "link-arg=-mios-version-min=11.0",
    "-C", "panic=abort",
    "-C", "force-frame-pointers=no"
]

[target.x86_64-apple-ios]
rustflags = [
    "-C", "link-arg=-mios-version-min=11.0",
    "-C", "panic=abort",
    "-C", "force-frame-pointers=no"
]

[target.aarch64-apple-ios-sim]
rustflags = [
    "-C", "link-arg=-mios-simulator-version-min=11.0",
    "-C", "panic=abort",
    "-C", "force-frame-pointers=no"
]

# Disable stack probes for iOS
[target.'cfg(target_os = "ios")']
rustflags = ["-C", "force-frame-pointers=no"]

# Test compilation optimizations
[build]
jobs = 8

# Test-specific optimizations
[profile.test]
opt-level = 1          # Basic optimizations for faster execution
debug = true           # Keep debug info for better error messages
debug-assertions = true # Keep assertions for correctness
overflow-checks = true  # Safety checks
lto = false            # Disable LTO for faster compilation
codegen-units = 8      # Parallel compilation