[target.aarch64-apple-ios]
rustflags = [
    "-C", "link-arg=-mios-version-min=11.0",
    "-C", "panic=abort",
    "-C", "force-frame-pointers=no"
]

[target.x86_64-apple-ios]
rustflags = [
    "-C", "link-arg=-mios-version-min=11.0",
    "-C", "panic=abort",
    "-C", "force-frame-pointers=no"
]

[target.aarch64-apple-ios-sim]
rustflags = [
    "-C", "link-arg=-mios-simulator-version-min=11.0",
    "-C", "panic=abort",
    "-C", "force-frame-pointers=no"
]

# Disable stack probes for iOS
[target.'cfg(target_os = "ios")']
rustflags = ["-C", "force-frame-pointers=no"]