[target.aarch64-apple-ios]
rustflags = ["-C", "link-arg=-mios-version-min=11.0"]

[target.x86_64-apple-ios]
rustflags = ["-C", "link-arg=-mios-version-min=11.0"]

[target.aarch64-apple-ios-sim]
rustflags = ["-C", "link-arg=-mios-simulator-version-min=11.0"]