name: lightning_db_example
description: Demonstrates how to use the Lightning DB Flutter plugin.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  lightning_db:
    path: ../
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  rxdart: ^0.27.7
  sqflite_common_ffi: ^2.3.0
  fl_chart: ^0.66.0
  http: ^1.1.0
  crypto: ^3.0.3
  # realm: ^1.6.0  # Uncomment when ready to test with Realm

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.0
  freezed: ^2.4.0
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true